<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <?php echo $this->getMethod()->getConfigData('selection_message');?>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
<script>
setTimeout(function(){ 
				if($('shipping-progress-opcheckout') != undefined) {
					$('shipping-progress-opcheckout').hide();
				}
}, 3100);
</script>